{"name": "Test User creation endpoint", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create user: 406 {'code': '1204', 'message': 'User exists!'}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code", "trace": "@allure.title(\"Test User creation endpoint\")\n    def test_create_user():\n        global user_id\n        with allure.step(\"Sending POST request to User creation endpoint\"):\n            response = requests.post(f\"{BASE_URL}/User\", json=example_user)\n>           assert response.status_code == 201, f\"Failed to create user: {response.status_code} {response.json()}\"\nE           AssertionError: Failed to create user: 406 {'code': '1204', 'message': 'User exists!'}\nE           assert 406 == 201\nE            +  where 406 = <Response [406]>.status_code\n\nswagger_test.py:20: AssertionError"}, "steps": [{"name": "Sending POST request to User creation endpoint", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create user: 406 {'code': '1204', 'message': 'User exists!'}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code\n", "trace": "  File \"C:\\Users\\Romidamaru\\Desktop\\Основная\\Коды\\swagger_test\\swagger_test.py\", line 20, in test_create_user\n    assert response.status_code == 201, f\"Failed to create user: {response.status_code} {response.json()}\"\n"}, "start": 1715449679852, "stop": 1715449680736}], "start": 1715449679851, "stop": 1715449680737, "uuid": "a1409fdc-1ef2-40d6-a637-69a33baf6c03", "historyId": "c01bf43f7014baab292466ea3da27252", "testCaseId": "c01bf43f7014baab292466ea3da27252", "fullName": "swagger_test#test_create_user", "labels": [{"name": "suite", "value": "swagger_test"}, {"name": "host", "value": "Romidamaru"}, {"name": "thread", "value": "2568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "swagger_test"}]}