{"name": "Test User creation endpoint", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка: 406 {'code': '1204', 'message': 'User exists!'}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code", "trace": "@allure.title(\"Test User creation endpoint\")\n    def test_create_user():\n        with allure.step(\"Sending POST request to User creation endpoint\"):\n            response = requests.post(f\"{BASE_URL}/User\", json=example_user)\n    \n        with allure.step(\"Verifying response status code\"):\n>           assert response.status_code == 201, f\"Ошибка: {response.status_code} {response.json()}\"\nE           AssertionError: Ошибка: 406 {'code': '1204', 'message': 'User exists!'}\nE           assert 406 == 201\nE            +  where 406 = <Response [406]>.status_code\n\nswagger_test.py:36: AssertionError"}, "steps": [{"name": "Sending POST request to User creation endpoint", "status": "passed", "start": 1715448106361, "stop": 1715448107202}, {"name": "Verifying response status code", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка: 406 {'code': '1204', 'message': 'User exists!'}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code\n", "trace": "  File \"C:\\Users\\Romidamaru\\Desktop\\Основная\\Коды\\swagger_test\\swagger_test.py\", line 36, in test_create_user\n    assert response.status_code == 201, f\"Ошибка: {response.status_code} {response.json()}\"\n"}, "start": 1715448107202, "stop": 1715448107202}], "start": 1715448106361, "stop": 1715448107203, "uuid": "536bcabb-8a67-4829-901d-a5027220f831", "historyId": "c01bf43f7014baab292466ea3da27252", "testCaseId": "c01bf43f7014baab292466ea3da27252", "fullName": "swagger_test#test_create_user", "labels": [{"name": "suite", "value": "swagger_test"}, {"name": "host", "value": "Romidamaru"}, {"name": "thread", "value": "7300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "swagger_test"}]}