{"name": "Test Authorized endpoint - Failed Authentication", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nassert {'code': '120...r not found!'} == {'message': 'User not found!'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': '1207'}\n  Use -v to get more diff", "trace": "@allure.title(\"Test Authorized endpoint - Failed Authentication\")\n    def test_authorized_failure():\n        invalid_user = {\"userName\": \"invaliduser\", \"password\": \"invalidpassword\"}\n        with allure.step(\"Sending POST request to Authorized endpoint with invalid credentials\"):\n            response = requests.post(f\"{BASE_URL}/Authorized\", json=invalid_user)\n    \n        with allure.step(\"Verifying response status code\"):\n            assert response.status_code in [400, 404], f\"Unexpected response status code: {response.status_code}\"\n    \n        with allure.step(\"Verifying response content\"):\n>           assert response.json() == {\"message\": \"User not found!\"}, f\"Unexpected response content: {response.json()}\"\nE           AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nE           assert {'code': '120...r not found!'} == {'message': 'User not found!'}\nE             \nE             Omitting 1 identical items, use -vv to show\nE             Left contains 1 more item:\nE             {'code': '1207'}\nE             Use -v to get more diff\n\nswagger_test.py:35: AssertionError"}, "steps": [{"name": "Sending POST request to Authorized endpoint with invalid credentials", "status": "passed", "start": 1715437324627, "stop": 1715437325594}, {"name": "Verifying response status code", "status": "passed", "start": 1715437325594, "stop": 1715437325594}, {"name": "Verifying response content", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nassert {'code': '120...r not found!'} == {'message': 'User not found!'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': '1207'}\n  Use -v to get more diff\n", "trace": "  File \"C:\\Users\\Romidamaru\\Desktop\\Основная\\Коды\\swagger_test\\swagger_test.py\", line 35, in test_authorized_failure\n    assert response.json() == {\"message\": \"User not found!\"}, f\"Unexpected response content: {response.json()}\"\n"}, "start": 1715437325594, "stop": 1715437325595}], "start": 1715437324626, "stop": 1715437325596, "uuid": "683893d9-de2e-49b6-ab91-31a03d808356", "historyId": "331f821270927c9d49ee8e0f347ddc90", "testCaseId": "331f821270927c9d49ee8e0f347ddc90", "fullName": "swagger_test#test_authorized_failure", "labels": [{"name": "suite", "value": "swagger_test"}, {"name": "host", "value": "Romidamaru"}, {"name": "thread", "value": "12684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "swagger_test"}]}