{"name": "Test Authorized endpoint - Failed Authentication", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nassert {'code': '120...r not found!'} == {'code': 0, '...ge': 'string'}\n  \n  Differing items:\n  {'code': '1207'} != {'code': 0}\n  {'message': 'User not found!'} != {'message': 'string'}\n  Use -v to get more diff", "trace": "@allure.title(\"Test Authorized endpoint - Failed Authentication\")\n    def test_authorized_failure():\n        invalid_user = {\"userName\": \"invaliduser\", \"password\": \"invalidpassword\"}\n        with allure.step(\"Sending POST request to Authorized endpoint with invalid credentials\"):\n            response = requests.post(f\"{BASE_URL}/Authorized\", json=invalid_user)\n    \n        with allure.step(\"Verifying response status code\"):\n            assert response.status_code in [400, 404], f\"Unexpected response status code: {response.status_code}\"\n    \n        with allure.step(\"Verifying response content\"):\n>           assert response.json() == {\"code\": 0, \"message\": \"string\"}, f\"Unexpected response content: {response.json()}\"\nE           AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nE           assert {'code': '120...r not found!'} == {'code': 0, '...ge': 'string'}\nE             \nE             Differing items:\nE             {'code': '1207'} != {'code': 0}\nE             {'message': 'User not found!'} != {'message': 'string'}\nE             Use -v to get more diff\n\nswagger_test.py:34: AssertionError"}, "steps": [{"name": "Sending POST request to Authorized endpoint with invalid credentials", "status": "passed", "start": 1715436914107, "stop": 1715436915087}, {"name": "Verifying response status code", "status": "passed", "start": 1715436915087, "stop": 1715436915087}, {"name": "Verifying response content", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response content: {'code': '1207', 'message': 'User not found!'}\nassert {'code': '120...r not found!'} == {'code': 0, '...ge': 'string'}\n  \n  Differing items:\n  {'code': '1207'} != {'code': 0}\n  {'message': 'User not found!'} != {'message': 'string'}\n  Use -v to get more diff\n", "trace": "  File \"C:\\Users\\Romidamaru\\Desktop\\Основная\\Коды\\swagger_test\\swagger_test.py\", line 34, in test_authorized_failure\n    assert response.json() == {\"code\": 0, \"message\": \"string\"}, f\"Unexpected response content: {response.json()}\"\n"}, "start": 1715436915087, "stop": 1715436915090}], "start": 1715436914107, "stop": 1715436915091, "uuid": "49c8d514-9d69-4c63-93a1-fc1377b0424f", "historyId": "331f821270927c9d49ee8e0f347ddc90", "testCaseId": "331f821270927c9d49ee8e0f347ddc90", "fullName": "swagger_test#test_authorized_failure", "labels": [{"name": "suite", "value": "swagger_test"}, {"name": "host", "value": "Romidamaru"}, {"name": "thread", "value": "8564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "swagger_test"}]}